### ISSUE TITLE
Es Draught, no Draft

### ISSUE THREAD

**Issue by foca** [datauy/back-end-birra#3]
As seen on http://birra.herokuapp.com/beers

Seguro es culpa de @picandocodigo.

**Comment by picandocodigo** [comment]
@foca yo no fui...

**Comment by foca** [comment]
Ah, claro, lavándote las manos en lugar de arreglar el problema. Classic @picandocodigo.

**Comment by foca** [comment]
(:kissing_heart:)

**Comment by EmilioCristalli** [comment]
Para mi se puede decir de las dos formas. Pero si alguien está seguro que draft está mal y quiere cambiarlo, adelante.

**Comment by picandocodigo** [comment]
Según [Wikipedia](https://en.wikipedia.org/wiki/Draught_beer):

> **Draught beer**, also spelt **draft**, is beer served from a cask or keg rather than from a bottle or can.

No cambia nada :beers:

**Comment by foca** [comment]
Malditos americanos con sus spellings alternativos para las cosas ¬¬

Oh well ¯\_(ツ)_/¯
